cosmic/cosmic/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("search/", include("search.urls", namespace="search")),
    path("feed/", include("feed.urls", namespace="feed")),
    path("", include("users.urls", namespace="users")),
    path('admin/', admin.site.urls),
]

cosmic/feed/urls.py
from django.urls import path, include
from . import views

app_name = "feed"

urlpatterns = [
    path("dashboard", views.dashboard_view, name="dashboard"),
    path("create_project", views.create_project_view, name="create_project"),
    path("project_post", views.project_post_view, name="project_post"),
    path("project_list", views.project_list_view, name="project_list"),
    path("project_contribution", views.project_contribution_view, name="project_contribution"),
    path("skills", views.skills_view, name="skills"),
    path("update_skills", views.update_skills_view, name="update_skills"),
    path("remove_proj", views.remove_proj_view, name="remove_proj"),
    path("update_project", views.update_project_view, name="update_project"),
    path("delete_project", views.delete_project_view, name="delete_project")
]

cosmic/search/urls.py
from django.urls import path
from . import views
app_name = "search"

urlpatterns = [
    path("", views.search_view, name="search"),
    path("save_project", views.save_project_view, name="save_project")
]

cosmic/users/urls.py
from django.urls import path, include
from . import views

app_name = "users"

urlpatterns = [
    path("", views.index_view, name="index"),
    path("register", views.register_view, name="register"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout")
]

cosmic/feed/models.py
from django.db import models
from users.models import CustomUser

# Create your models here.
class Project(models.Model):
    proj_id = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    proj_name = models.CharField(max_length=120)
    proj_desc = models.TextField()
    requirements = models.TextField()
    proj_links = models.TextField()

class SkillSet(models.Model):
    skill_id = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    skill_text = models.TextField()

class SavedProject(models.Model):
    saved_id = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    saved_proj_id = models.IntegerField()

cosmic/search/models.py
from django.db import models

# Create your models here.

cosmic/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class CustomUser(AbstractUser):
    email = models.EmailField(max_length=250, unique=True)
    is_developer = models.BooleanField(default=False)
    
    def __str__(self):
        return self.username

cosmic/feed/views.py
from django.shortcuts import render, redirect
from .models import Project, SavedProject

# Create your views here.
def dashboard_view(request):
    if request.user.is_authenticated:
        context = {
            "user": request.user
        }
        return render(request, "dashboard.html", context)
    else:
        return redirect("users:index")
    
def create_project_view(request):
    return render(request, "create_project.html")

def project_post_view(request):
    if request.method == "POST":
        data = request.user.project_set.create(
            proj_name = request.POST["name"],
            proj_desc = request.POST["description"],
            requirements = request.POST["requirements"],
            proj_links = request.POST["project_links"],
        )
        data.save()
        return redirect("feed:dashboard")
    
def project_list_view(request):
    data = Project.objects.filter(proj_id=request.user.id)
    context = {
        "data": data
    }
    return render(request, "project_list.html", context)

def project_contribution_view(request):
    proj_contributes = request.user.savedproject_set.all()
    projs = []

    for proj in proj_contributes:
        projs.extend(Project.objects.filter(pk=proj.saved_proj_id))
    
    context = {
        "projs": projs
    }
    return render(request, "project_contribution.html", context)

def skills_view(request):
    try:
        context = {
            "user_skills": request.user.skillset_set.all()[0]
        }
    except Exception:
        context = {
            "user_skills": ""
        }
    return render(request, "skills.html", context)

def update_skills_view(request):
    if request.method == "POST":
        request.user.skillset_set.update_or_create(defaults={"skill_text":request.POST["skills"]})
        return redirect("feed:skills")

def remove_proj_view(request):
    if request.method == "POST":
        saved_proj = SavedProject.objects.filter(saved_proj_id=int(request.POST["pid"]), saved_id=request.user)
        saved_proj.delete()
        return redirect("feed:dashboard")
    
def update_project_view(request):
    if request.method == "POST":
        Project.objects.filter(id=request.POST["pid"], proj_id=request.user).update(
            proj_name=request.POST["name"],
            proj_desc=request.POST["description"],
            requirements=request.POST["requirements"],
            proj_links=request.POST["project_links"],
        )
    return redirect("feed:project_list")

def delete_project_view(request):
    if request.method == "POST":
        Project.objects.filter(id=request.POST["pid"], proj_id=request.user).delete()
    return redirect("feed:project_list")

cosmic/search/views.py
from django.shortcuts import render, redirect
from feed.models import Project
from users.models import CustomUser
from feed.models import SkillSet
from django.db.models import Q

# Create your views here.
def search_view(request):
    if request.method == "GET":
        search_param = request.GET["search"]

        if request.user.is_developer:
            usernames = CustomUser.objects.filter(Q(username__icontains = search_param))
            usernames_by_skills = SkillSet.objects.filter(skill_text__icontains = search_param)
            context = {
                    "usernames": usernames,
                    "usernames_by_skills": usernames_by_skills,
                }
            return render(request, "search_res.html", context)
    
        projects = Project.objects.filter(
                Q(proj_name__icontains = search_param) |
                Q(proj_desc__icontains = search_param) |
                Q(requirements__icontains = search_param) |
                Q(proj_links__icontains = search_param)
        )
        cleaned_projects = []
        for project in projects:
            if not request.user.savedproject_set.filter(saved_proj_id = project.id):
                cleaned_projects.append(project)
                
        context = {
            "projects": cleaned_projects
        }
        return render(request, "search_res.html", context)

def save_project_view(request):
    if request.method == "POST":
        request.user.savedproject_set.create(saved_proj_id=int(request.POST["pid"]))

        return redirect("feed:dashboard")

cosmic/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from .models import CustomUser

# Create your views here.
def index_view(request):
    err = None
    return render(request, "index.html", {"err":err})

def register_view(request):
    if request.method == "POST":
        if request.POST["is_developer"] == "1":
            dev = 1
        else:
            dev = 0
            
        CustomUser.objects.create_user(username=request.POST["username"], password=request.POST["password"], email=request.POST["email"], is_developer=dev)

        return render(request, "register_success.html")
    return render(request, "index.html")

def login_view(request):
    if request.method == "POST":
        user = authenticate(username=request.POST["username"], password=request.POST["password"])

        if user is not None:
            login(request, user)
            return redirect("feed:dashboard")
        else:
            err = "Invalid Username/Password"
        
    else:
        err = None

    return render(request, "index.html", {"err":err})

def logout_view(request):
    logout(request)
    return redirect("users:index")

cosmic/feed/templates/create_project.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <link href="https://fonts.googleapis.com/css?family=Montserrat+Alternates:300,400,500,600" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'create_project.css' %}">
</head>
<body>
    <main>
    <form action="{% url 'feed:project_post' %}" method="post">
        {% csrf_token %}
        <label for="name">Project Name</label>
        <input type="text" name="name" required>
        <label for="description">Description</label>
        <textarea name="description" required></textarea>
        <label for="requirements">Requirements</label>
        <textarea name="requirements" required></textarea>
        <label for="project_links">Links</label>
        <textarea name="project_links" required></textarea>
        <input type="submit" value="Submit" class="button">
        <a href="{% url 'feed:dashboard' %}" class="button">Go Back</a>
        
    </form>
</main>

</body>
</html>

cosmic/feed/templates/dashboard.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">

    <link href="https://fonts.googleapis.com/css?family=Montserrat+Alternates:300,400,500,600" rel="stylesheet">
    <link href="https://maxcdn.icons8.com/fonts/line-awesome/1.1/css/line-awesome-font-awesome.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'dashboard.css' %}">
</head>
<body>
    <main>
        <h1 style="font-size: 50px; top: 30px; left: 10px; position: absolute;">Welcome back, {{ user.username }} !!!</h1>
        <a class="logout-btn" style="font-size: 20px; top: 30px; right: 10px; position: absolute;" href="{% url 'users:logout' %}">Logout</a>
        <div class="container">

            {% if user.is_developer %}
                <h1>Looking to find project collaborators?</h1> <br/>
            {% else %}
                <h1>Looking for projects?</h1> <br/>
            {% endif %}

            <div class="search-box">
            <div class="search-icon"><i class="fa fa-search search-icon"></i></div>
            {% csrf_token %}
            <form action="{% url 'search:search' %}" method="get" class="search-form">
                <input type="text" placeholder="Search" id="search" name="search" autocomplete="off">
            </form>
            <svg class="search-border" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:a="http://ns.adobe.com/AdobeSVGViewerExtensions/3.0/" x="0px" y="0px" viewBox="0 0 671 111" style="enable-background:new 0 0 671 111;"
                xml:space="preserve">
                <path class="border" d="M335.5,108.5h-280c-29.3,0-53-23.7-53-53v0c0-29.3,23.7-53,53-53h280"/>
                <path class="border" d="M335.5,108.5h280c29.3,0,53-23.7,53-53v0c0-29.3-23.7-53-53-53h-280"/>
            </svg>
            <div class="go-icon"><i class="fa fa-arrow-right"></i></div>
        </div>

        {% if user.is_developer %}
            <div style="position: absolute; top: 350px; left: 55%; transform: translate(-50%, 50%);width: 100%;">
                <a style="color: black; padding: 100px; " class="btn" href="{% url 'feed:create_project' %}">Create Project</a>
                <a style="color: black; padding: 100px; " class="btn" href="{% url 'feed:project_list' %}">Your Projects</a>
            </div>

        {% else %}
            <div style="display:flex;">
                <a style="color: black; padding: 80px;" class="btn" href="{% url 'feed:project_contribution' %}">Project Contribution</a>
                <a style="color: black; padding: 80px;" class="btn" href="{% url 'feed:skills' %}">Add/Update Skills</a>
            </div>
        {% endif %}
    </main>
</body>
</html>

cosmic/feed/templates/project_contribution.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <title>Your Project List</title>
    <link rel="stylesheet" href="{% static 'project_contribution2.css' %}">
</head>
<body>
    {% if not projs %}
        <h1>No results</h1>
    {% else %}
    <uL>
        {% for proj in projs %}
        <li>
            <form action="{% url 'feed:remove_proj' %}" method="post">
                <input type="hidden" value="{{ proj.id }}" name="pid">
                {% csrf_token %}
                <h2>{{ proj.proj_name }}</h2> <!-- Bold the project name -->
                {{ proj.proj_desc }}<br>
                {{ proj.requirements }}<br>
                {{ proj.proj_links }}        
                <a href="mailto:{{ proj.proj_id.email }}">Send email to the Author</a>     
                <input type="submit" value="Remove">

                <a class="proj_links" href="{{ proj.proj_links }}">{{ proj.proj_links }}</a> <!-- Apply the style for project links -->
                <button class="remove-button" >Remove</button> <!-- Apply the style for the button -->
            </form>
        </li>
        {% endfor %}
    {% endif %}
    </ul>
    <a href="{% url 'feed:dashboard' %}" class="x">Go Back</a>
</body>
</html>

cosmic/feed/templates/project_list.html
<!DOCTYPE html>
<html>
<head>
    <style>
        /* Add your CSS styles here */
        body {
            font-family: Arial, sans-serif;
        }
        ul {
            list-style-type: none;
        }
        li {
            margin-bottom: 20px;
        }
        form {
            border: 2px solid #ccc;
            padding: 30px;
            background-color: #f9f9f9;
        }
        label {
            display: block;
            margin-top: 10px;
        }
        input[type="text"],
        textarea {
            width: 100%;
            padding: 10px;
            margin-left: 2px;

            margin-bottom: 10px;
            border: 1px solid #ccc;
        }
        .button {
            background-color: #4CAF50;
            color: white;
            padding: 10px 20px;
            border: none;
            cursor: pointer;
        }
        .x {
            background-color: #007BFF;
            color: #ffffff;
            padding: 10px 50px;
            border: none;
            font-size: 17px;
            border-radius: 5px;
            cursor: pointer;
            display: inline-block;
            text-decoration: none;
            font-family: sans-serif;
            text-align: center; /* Center the text horizontally */
        }
        .button:hover {
            background-color: #45a049;
        }
        .center-text {
            text-align: center; /* Center the text horizontally */
        }
    </style>
</head>
<body>
    {% if data %}
    <ul>
    {% for datum in data %}
        <li>
            <form action="{% url 'feed:update_project' %}" method="post">
                {% csrf_token %}
                <input type="hidden" value="{{ datum.id }}" name="pid">
                <label for="name">Project Name</label>
                <input type="text" name="name" value="{{ datum.proj_name }}" required>
                <label for="description">Description</label>
                <textarea name="description" required>{{ datum.proj_desc }}</textarea>
                <label for="requirements">Requirements</label>                    <textarea name="requirements" required>{{ datum.requirements }}</textarea>
                <label for="project_links">Links</label>
                <textarea name="project_links" required>{{ datum.proj_links }}</textarea>
                <input type="submit" value="Edit" class="button">
            </form>
            <form action="{% url 'feed:delete_project' %}" method="post">
                {% csrf_token %}
                <input type="hidden" value="{{ datum.id }}" name="pid">
                <input type="submit" value="Delete" class="button">
            </form>

        </li>
    {% endfor %}
    </ul>
{% else %}
    <h1>You have no projects</h1>
{% endif %}
    <div class="center-text"> <!-- Create a container for centering text -->
        <a href="{% url 'feed:dashboard' %}" class="x">Go Back</a>
    </div>
</body>
</html>

cosmic/feed/templates/skills.html
<!DOCTYPE html>
<html>
<head>
    <style>
        /* Style the form container */
        .form-container {
            margin: 0 auto; /* Center the form horizontally */
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
            height: 100vh; /* Center vertically within the viewport */
            text-align: center; /* Center text within the container */
            font-family: sans-serif; /* Set the font to sans-serif */
            background-color: #f9f9f9; /* Set the background color */
        }

        /* Style the label */
        label {
            display: block; /* Make the label a block element */
            margin-bottom: 10px;
            font-size: 20px; /* Set the font size */
            font-family: sans-serif; /* Set the font to sans-serif */
        }

        /* Style the textarea */
        textarea {
            width: 100%;
            font-family: sans-serif; /* Set the font to sans-serif */
            padding: 20px;
            font-size: 20px; /* Set the font size */
            margin-bottom: 10px;
            border: 1px solid #ccc;
            border-radius: 4px;
        }

        /* Style both the submit button and Go Back link */
        input[type="submit"],
        a {
            background-color: #007BFF; /* Set the background color to #007BFF */
            color: #ffffff; /* Set the text color to white */
            padding: 10px 20px;
            border: none;
            font-size: 17px; /* Set the font size */
            border-radius: 4px;
            cursor: pointer;
            display: inline-block; /* Make them inline block elements */
            text-decoration: none;
            font-family: sans-serif; /* Set the font to sans-serif */
            margin-right: 10px; /* Add space between the button and the link */
        }
    </style>
</head>
<body>
    <div class="form-container">
        <form action="{% url 'feed:update_skills' %}" method="post">
            {% csrf_token %}
            <label for="skills">Your skills</label>
            <textarea name="skills">{{ user_skills.skill_text }}</textarea>
            <input type="submit" value="Add/Update">
            <a href="{% url 'feed:dashboard' %}">Go Back</a>
        </form>
    </div>
</body>
</html>

cosmic/search/templates/search_res.html
<!DOCTYPE html>
<html>
<head>
    <style>
        ul {
            list-style-type: none;
            padding: 0;
            font-family: 'Montserrat Alternates', sans-serif;
        }
        li {
            margin-bottom: 20px;
            border: 1px solid #ccc;
            padding: 40px;
            font-family: 'Montserrat Alternates', sans-serif;
            position: relative; /* Add this line to set the position for relative positioning */
        }
        form {
            display: inline;
            font-family: 'Montserrat Alternates', sans-serif;
        }
        h1 {
            color: #FF5733;
            font-family: 'Montserrat Alternates', sans-serif;
        }
        /* Style for the "Save" button */
        .save-button {
            background-color: #4CAF50;
            color: #ffffff;
            padding: 10px 20px;
            border: none;
            font-size: 15px;
            border-radius: 5px;
            cursor: pointer;
            font-family: 'Montserrat Alternates', sans-serif;
            position: absolute; /* Position the button absolutely within the list item */
            top: 10px; /* Adjust the top position as needed */
            right: 10px; /* Adjust the right position as needed */
        }
        /* Style for the "Send email" button */
        .send-email-button {
            background-color: #4CAF50;
            color: #ffffff;
            padding: 10px 20px;
            border: none;
            font-size: 15px;
            border-radius: 5px;
            cursor: pointer;
            font-family: 'Montserrat Alternates', sans-serif;
            margin-left: 20px; /* Add margin to separate it from the project name */
        }
        /* Style for the "Go Back" link */
        .go-back {
            background-color: #007BFF;
            color: #ffffff;
            padding: 10px 50px;
            border: none;
            font-size: 17px;
            border-radius: 5px;
            cursor: pointer;
            display: inline-block;
            text-decoration: none;
            font-family: 'Montserrat Alternates', sans-serif;
            text-align: center;
        }
    </style>
</head>
<body>
{% if projects %}
    <ul>
        {% for project in projects %}
            <li>
            <form action="{% url 'search:save_project' %}" method="post">
                {% csrf_token %}
                <input type="hidden" name="pid" value="{{ project.id }}">
                <div>
                    {{ project.proj_name }}
                    <a href="mailto:{{ project.proj_id.email }}" class="send-email-button">Send email</a>
                </div>
                {{ project.proj_desc }}<br>
                {{ project.requirements }}<br>
                {{ project.proj_links }}
                <input type="submit" value="Save" class="save-button">
            </form>
            </li>
        {% endfor %}
    </ul>
{% elif usernames or usernames_by_skills %}
    <ul>
        {% for user in usernames %}
            <li>
                {{ user.username }}
                <a href="mailto:{{ user.email }}" class="send-email-button">Send email</a>
            </li>
        {% endfor %}
        {% for user in usernames_by_skills %}
            <li>
                {{ user.skill_id }}
                <a href="mailto:{{ user.email }}" class="send-email-button">Send email</a>
            </li>
        {% endfor %}
    </ul>
{% else %}
    <h1>No results</h1>
{% endif %}

<a href="{% url 'feed:dashboard' %}" class="go-back">Go Back</a>
</body>
</html>

cosmic/users/templates/index.html
{% load static %}
<!DOCTYPE html>
<html>
    <style>h2,h5 {
        text-align: center;
    }</style>
    <link rel="stylesheet" href="{% static 'index2.css' %}">
<body>
    <h2 >Cosmic</h2>
    <h5 >A Marketspace for Open Science Projects</h5>

    <div style="display: grid;
    grid-template-columns: auto auto auto auto;">
        <div style="margin-top: 100px;">
            <h2 style="text-align: center; color: rgb(0, 0, 0)">Sign up</h2>
            <form class="su" action="{% url 'users:register' %}" method="post">
                {% csrf_token %}
                <div style="margin-left: 100px;">
                    <input class="user-su" type="text" name="username" placeholder="Username" required> <br />
                    <input class="pass-su" type="password" name="password" placeholder="Password" required> <br />
                    <input class="email-su" type="email" name="email" placeholder="Email" required> <br />
                </div>
                <h4 style="text-align: center; color: rgb(0, 0, 0)">Select Account type</h4>
                <div style="text-align: center; margin-bottom: 30px; color: rgb(5, 5, 5)" class="rad" >
                    <input type="radio" name="is_developer" value="1" id="dev" required>
                        <label for="dev">Organizations</label>
                    <input type="radio" name="is_developer" value="0" id="con" required>
                        <label for="con">Contributors</label> <br/>
                </div>
                <input style="margin-left: 180px;   " class="submit-su" type="submit" value="Register">
            </form>
        </div>

        <div class="vl" ><h2 style="margin-left: -20px; display: block; background-color: #f9f9f9; color: #4CAF50;">OR</h2></div>

        <div style="margin-top: 100px;">
            <h2 style="text-align: center; color: rgb(0, 0, 0);">Sign in</h2>
            <form class="si" action="{% url 'users:login' %}" method="post">
                {% csrf_token %}
                <p style="color: rgb(0, 0, 0); margin: 10px; font-size: 16px;">Username</p>
                <input class="user-si" type="text" name="username" placeholder="Username" required>
                <p style="color: rgb(0, 0, 0); margin: 10px; font-size: 16px;">Password</p>
                <input class="pass-si" type="password" name="password" placeholder="Password" required>
                {% if err %}
                    <p style="color: wheat; margin: 10px; font-size: 16px; text-align: center; font-weight: 600; " class="error-message">{{ err }}</p>
                {% endif %}
                <input class="submit-si" type="submit" value="Login">
            </form>
        </div>
    </div>
</body>
</html>

cosmic/users/templates/register_success.html
<html>
  <head>
    <link href="https://fonts.googleapis.com/css?family=Nunito+Sans:400,400i,700,900&display=swap" rel="stylesheet">
  </head>
    <style>
        body {
            text-align: center;
            padding: 40px 0;
            background-color: #f9f9f9;
        }
        h1 {
            color: #88B04B;
            font-family: "Nunito Sans", "Helvetica Neue", sans-serif;
            font-weight: 900;
            font-size: 40px;
            margin-bottom: 10px;
        }
        p {
            color: #88B04B;
            font-family: "Nunito Sans", "Helvetica Neue", sans-serif;
            font-size:20px;
            margin: 0;
        }
        a {
            text-decoration: none;
            font-family: "Nunito Sans", "Helvetica Neue", sans-serif;
            background-color: #88B04B;
            color: white;
            padding: 10px 20px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
        }
        i {
            color: #9ABC66;
            font-size: 100px;
            line-height: 200px;
            margin-left:-15px;
        }
        .card {
          background: #dddbdb;
            padding: 60px;
            border: 2px solid #087536; /* Add a 2px solid red border to the square */
            box-shadow: 0 2px 3px #4d5054;
            display: inline-block;
            margin: 0 auto;
        }
    </style>
    <body>
      <div class="card">
      <div style="border-radius:200px; height:200px; width:200px; background: #64675f; margin:0 auto;">
        <i class="checkmark">✓</i>
      </div>
        <h1>You're all set!</h1> 
        <p>Please go back and log in</p> <br/>
        <a href="{% url 'users:index' %}">Go back</a>
      </div>
    </body>
</html>